### ISSUE TITLE
Performance comparisons / benchmarks

### ISSUE THREAD

**Issue by banagale** [Mng-dev-ai/drf-turbo#7]
I saw this pop up in the django news newsletter. I could have used this on a project a while back where we wanted more performance out of serialization in DRF.

Can someone give sort of a high level idea of what kind of performance improvements one might expect by swapping this in for what comes with DRF today?

**Comment by maxzod** [comment]
its listed in the [docs ](https://drf-turbo.readthedocs.io/en/latest/performance.html?fbclid=IwAR2kUbUUUWir8vMYPXhFIG7ggsydLlVmtqHlH2yRKm6k1SuvUhm82AyJGnY)😀

**Comment by banagale** [comment]
So it is! My eye must have skimmed right over that.

Since most folks will be comparing this to DRF's standard serializer, perhaps it would be good to surface the this relative difference in the Readme directly. 

For example, the readme performance section could say:

Using Pydantic's benchmarking code, `drf-turbo` has shown to perform serialization nearly 86% faster than DRF's included serializer. 

To see more benchmarking information, visit the [benchmarks section](https://drf-turbo.readthedocs.io/en/latest/performance.html?fbclid=IwAR2kUbUUUWir8vMYPXhFIG7ggsydLlVmtqHlH2yRKm6k1SuvUhm82AyJGnY) of the docs.

Then on the benchmark page show the relative performance in a table [similar to Pydantic's](https://pydantic-docs.helpmanual.io/benchmarks/) or just leave it but link the benchmarking code used. 

I can offer a PR if helpful.

 best=856.090μs/iter avg=885.471μs/iter stdev=39.377μs/iter version=3.12.4
drf-turbo best=111.754μs/iter avg=113.794μs/iter stdev=1.274μs/iter version=0.1.1

**Comment by Mng-dev-ai** [comment]
Yeah sure Pull-Requests are welcomed. 
There's also an opening PR to add drf-turbo to pydantic benchmarks which you can see from here
https://github.com/samuelcolvin/pydantic/pull/3404
